# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cory Zue
author: Cory Zue
email: cory.zue@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Cory Zue is an American software developer and technologist living in Cape Town, South Africa.
  He writes about his sabbatical from his CTO job as he tries to launch a product.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://czue.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bower_components
  - s3_website.yml
google_analytics: UA-94102737-1
